--@Author='Aditya Narayan'
-- Contest Leaderboard
	SELECT H.*, SUM(INNERSCORE) AS TOTAL FROM 
		(  
			SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS INNERSCORE FROM SUBMISSIONS
			GROUP BY HACKER_ID, CHALLENGE_ID
		)S
		INNER JOIN HACKERS H ON S.HACKER_ID = H.HACKER_ID
	GROUP BY H.HACKER_ID, H.NAME
	HAVING SUM(INNERSCORE) > 0
	ORDER BY SUM(INNERSCORE) DESC, H.HACKER_ID;