--@Author='Aditya Narayan'
-- Type of Triangle
	SELECT CASE
    	WHEN A+B>C AND B+C>A AND A+C>B THEN
		CASE
			WHEN A=B AND B=C AND C=A THEN 'Equilateral'
			WHEN A=B OR B=C OR C=A THEN 'Isosceles'
			ELSE 'Scalene'
		END
		ELSE 'Not A Triangle'
	END
	FROM TRIANGLES;

-- The PADS
	SELECT NAME+"("+LEFT(OCCUPATION,1)+")" FROM OCCUPATIONS ORDER BY NAME ASC;
	SELECT "There are a total of " + STR(COUNT(OCCUPATION)) + " " +LOWER(OCCUPATION) +"s." 
    FROM OCCUPATIONS 
    GROUP BY OCCUPATION
    ORDER BY COUNT(OCCUPATION),OCCUPATION;

-- Occupations
    SELECT [DOCTOR], [PROFESSOR], [SINGER], [ACTOR] FROM
        (SELECT ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) ROW_NUM, [NAME], [OCCUPATION] FROM OCCUPATIONS) AS SOURCE 
    PIVOT
        ( MIN([NAME]) FOR [OCCUPATION] IN ([DOCTOR],[PROFESSOR],[SINGER],[ACTOR]) ) AS PVT
    ORDER BY ROW_NUM;
		
-- Binary Tree Nodes
	SELECT N,
		CASE 
			WHEN P IS NULL THEN "Root"
			WHEN N IN (SELECT P FROM BST) THEN "Inner"
			ELSE "Leaf"
		END
	FROM BST
	ORDER BY N
	