--@Author='Aditya Narayan'
-- Placements
	WITH CTE AS (
    SELECT S1.ID AS ID, S1.NAME AS NAME, P1.SALARY AS SALARY, F1.FRIEND_ID AS FRIEND_ID, P2.SALARY AS FRIEND_SALARY
    FROM STUDENTS S1 JOIN PACKAGES P1 ON S1.ID = P1.ID
        JOIN FRIENDS F1 ON S1.ID = F1.ID
        JOIN PACKAGES P2 ON F1.FRIEND_ID = P2.ID
	)
	SELECT NAME FROM CTE WHERE FRIEND_SALARY > SALARY
	ORDER BY FRIEND_SALARY